### ISSUE TITLE
Удалить закоменченый тест. 

### ISSUE THREAD

**Issue by anatoliyfedorenko** [go-internship/HeroVsDragon#25]
https://github.com/go-internship/HeroVsDragon/blob/840a5cc54d0d1a5746127cfad0f6ae4d1b454f0d/HeroVsDragon_test.go#L5

этот тест вообще не о чём. не надо проверять рандом. и не надо оставлять закомменченый код в репозитории. если он тебе понадобится, найдешь его по истории. не захламляй файлы.

**Comment by sula7** [comment]
Логично, что не логично рандом проверять. got и want одно и то же получат)
@sula7 Удалил
