### ISSUE TITLE
Изучить библиотеку testify 

### ISSUE THREAD

**Issue by anatoliyfedorenko** [go-internship/HeroVsDragon#26]
https://github.com/go-internship/HeroVsDragon/blob/840a5cc54d0d1a5746127cfad0f6ae4d1b454f0d/HeroVsDragon_test.go#L20

Чтобы везде не писать так лучше используй библиотеку нормальную 
https://github.com/stretchr/testify 

почитай документацию прежде чем использовать

**Comment by sula7** [comment]
Изучил, применил. Библа действительно, упрощает тестирование
